import { Toaster } from "@/components/ui/sonner";
import { Lato } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const texta = localFont({
  src: [
    {
      path: "./fonts/TextaRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/TextaBold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-texta",
  display: "swap",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
  display: "swap",
});
export const metadata = {
  title: "Splendor Eid Souk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${texta.className} ${lato.variable} antialiased`}>
        {children}
        <Toaster position="top-right" richColors theme={"light"} />
      </body>
    </html>
  );
}
