import { Toaster } from "@/components/ui/sonner";
import { Barlow, Public_Sans } from "next/font/google";
import "./globals.css";

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
  variable: "--font-barlow",
  display: "swap",
});

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
  variable: "--font-publicSans",
  display: "swap",
});

export const metadata = {
  title: "Employer Portal-",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${publicSans.className} ${barlow.variable}  antialiased`}
      >
        {children}
        <Toaster position="top-right" richColors theme={"light"} />
      </body>
    </html>
  );
}
